defaults:
  - _self_
  - pretrain: pretrain
  - finetune@finetune.canc_type_class: canc_type_class
  - finetune@finetune.canc_type_class_33: canc_type_class_33
  - finetune@finetune.deconv: deconv
  - finetune@finetune.surv_pred: surv_pred
  - finetune@finetune.disease_class: disease_class
  - finetune@finetune.gene_essent: gene_essent
  - finetune@finetune.drug_resp: drug_resp

task: pretrain
