defaults:
  - _self_
  - pretrain: pretrain
  - finetune@finetune.canc_type_class: canc_type_class
  - finetune@finetune.canc_type_class_33: canc_type_class_33
  - finetune@finetune.deconv: deconv

task: pretrain
