pretrained_model_paths:
  pretrain_sc:
  pretrain_bulk:
  preadapt_sc:
  preadapt_bulk:
tcga_data_dir:
gene_list_path: ../data/gene_list.txt


cohorts: [BRCA, BLCA, GBM, LGG, LUAD, UCEC]
merge_gbm_lgg: true
normalized: false
min_genes: 200
cv_folds: 5
random_seed: 42

finetune_mode: head_only
burn_in_epochs: 3
epochs: 10
batch_size: 2
grad_accumulation_steps: 3
head_learning_rate: 1e-4
backbone_learning_rate: 1e-6
max_grad_norm: 1e6

first_cycle_steps: 15
cycle_mult: 2
min_lr: 1e-6
min_lr_ratio:
warmup_steps: 5
gamma: 0.9
