pretrained_model_paths:
  pretrain_sc:
  pretrain_bulk:
  preadapt_sc:
  preadapt_bulk:
pseudo_bulk_data_path:

finetune_mode: head_only
burn_in_epochs: 3
loss: kl

cv_folds: 10
split_by_context: true
context_columns: [dataset_id, donor_id, tissue_general]
random_seed: 42

epochs: 10
batch_size: 2
grad_accumulation_steps: 3
head_learning_rate: 1e-4
backbone_learning_rate: 1e-6
max_grad_norm: 1e6

head_hidden_dim: 128
head_dropout: 0.0

first_cycle_steps: 15
cycle_mult: 2
min_lr: 1e-6
min_lr_ratio:
warmup_steps: 5
gamma: 0.9
